version: "3.3"

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.21.0.255/24
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181"
    restart: on-failure
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      frontend:
  meta1:
    image: jiangxianfu/pegasus-docker:latest
    ports:
      - 34601:34601
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - meta1-data-volume:/pegasus/data
    command:
      - meta
    privileged: true
    networks:
      frontend:
        ipv4_address: 172.21.0.11
    restart: on-failure
  replica1:
    image: jiangxianfu/pegasus-docker:latest
    ports:
      - 34801
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - replica1-data-volumne:/pegasus/data
      - replica1-slog-volumne:/pegasus/slog
    command:
      - replica
    privileged: true
    restart: on-failure
    networks:
      frontend:
  collector1:
    image: jiangxianfu/pegasus-docker:latest
    ports:
      - 34101
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - collector1-data-volumne:/pegasus/data
    command:
      - collector
    privileged: true
    restart: on-failure
    networks:
      frontend:
volumes:
  meta1-data-volume:
  replica1-data-volumne:
  replica1-slog-volumne:
  collector1-data-volumne:
